.set ALIGN_LOADED_MODULES_ON_PAGE_BOUNDARIES, 1
.set PROVIDE_MEMORY_MAP, 1 << 1
.set MULTIBOOT_FLAGS, ALIGN_LOADED_MODULES_ON_PAGE_BOUNDARIES | PROVIDE_MEMORY_MAP
.set MAGIC, 0x1badb002
.set CHECKSUM, - (MAGIC + MULTIBOOT_FLAGS)

.section .multiboot
.align 4
.long MAGIC
.long MULTIBOOT_FLAGS
.long CHECKSUM

%include "./boot-stub.asm"
