ALIGN_LOADED_MODULES_ON_PAGE_BOUNDARIES equ 1
PROVIDE_MEMORY_MAP equ 1 << 1
MULTIBOOT_FLAGS equ ALIGN_LOADED_MODULES_ON_PAGE_BOUNDARIES | PROVIDE_MEMORY_MAP
MAGIC equ 0x1badb002
CHECKSUM equ -(MAGIC + MULTIBOOT_FLAGS)

section .multiboot
align 4
dd MAGIC
dd MULTIBOOT_FLAGS
dd CHECKSUM